export { SceneCanvas } from './SceneCanvas.js'
export { RoomScene } from './RoomScene.js'
export { RoomModel, VM_SLOT_PREFIX, TITLE_PILL_PREFIX } from './RoomModel.js'
export { HERO_SLOT_ID } from './slotIds.js'
export type { ExtractedSlot, TitleAnchor } from './RoomModel.js'
export { ZoneTitle } from './ZoneTitle.js'
export { ZONE_TITLES } from './zoneTitles.js'
export { buildRoomProps, buildRoomDataProps } from './roomUtils.js'
export { SlotFrame } from './SlotFrame.js'
export { Portal } from './Portal.js'
export { FloorPortal } from './FloorPortal.js'
export { NavController } from './NavController.js'
export type { RoomBounds, CameraState } from './NavController.js'
export { useGyroToggle } from './useGyroToggle.js'
export { RoomLighting } from './RoomLighting.js'
export { getPerfConfig, shouldUseFallback } from './PerfGuard.js'
export { loadTexture, preloadUrls, disposeRoom } from './TextureManager.js'
export { getRoomDimensions, getRoomSurfaces } from './templates.js'
export { getLightConfig } from './lighting.js'
