export { SceneCanvas } from './SceneCanvas.js'
export { RoomScene } from './RoomScene.js'
export { RoomModel } from './RoomModel.js'
export { buildRoomProps, buildRoomDataProps } from './roomUtils.js'
export { SlotFrame } from './SlotFrame.js'
export { Portal } from './Portal.js'
export { NavController } from './NavController.js'
export type { RoomBounds } from './NavController.js'
export { useGyroToggle } from './useGyroToggle.js'
export { RoomLighting } from './RoomLighting.js'
export { getPerfConfig, shouldUseFallback } from './PerfGuard.js'
export { loadTexture, preloadUrls, disposeRoom } from './TextureManager.js'
export { getRoomDimensions, getRoomSurfaces } from './templates.js'
export { getLightConfig } from './lighting.js'
