export { SceneCanvas } from './SceneCanvas.js'
export { RoomScene, buildRoomProps } from './RoomScene.js'
export { SlotFrame } from './SlotFrame.js'
export { Portal } from './Portal.js'
export { NavController, useGyroToggle } from './NavController.js'
export { RoomLighting } from './RoomLighting.js'
export { getPerfConfig, shouldUseFallback } from './PerfGuard.js'
export { loadTexture, preloadUrls, disposeRoom } from './TextureManager.js'
export { getRoomDimensions, getRoomSurfaces } from './templates.js'
export { getLightConfig } from './lighting.js'
